apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # base64 - postgres = cG9zdGdyZXM=
  JWT_SECRET: cG9zdGdyZXM=
  # base64 - EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
