apiVersion: v1
kind: Secret # tipo
metadata:
  name: postgres-secrets # para identificarlo y poderlo usar (no usa el nombre del archivo)
type: Opaque # para que no se pueda ver
data:
  # base64 - postgres
  DB_USER: cG9zdGdyZXM=
  # base64 - EstoEsUnPasswordSecreto
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
# INFO - no puedes usar valores sin base64 no lo permite
